### PR TITLE
fix: update @webcomponents/template

### LINKED ISSUE #36: npm install skatejs-web-components is broken
When installing the most recent version of `skatejs-web-components` with npm I'm getting the error:

`Invalid Package: expected @webcomponents/template but found template`.

Node version: `7.5.0`
Npm version: `4.1.2`

### PR DESCRIPTION
**Pull request by devopsmariocom**
to revision with proper package name, so npm install works again

Closes #36

### CODE REVIEW

**Review by treshugart — APPROVED** [review]
LGTM. Added you as a member. Feel free to merge at your convenience when build is green :)

**Comment by devopsmariocom** [comment]
Great thanks! Will do, but seems that information about passed build didn't get thru. Can you please re run build or force merge it as admin.

Thanks

**Comment by Hotell** [comment]
I would be cautions with this. Only thing that needs to be changed IMHO is pointing to new `@webcomponents/template` hash. Will verify ASAP.

DO NOT MERGE (YET)!

**Comment by Hotell** [comment]
Oh right, you just changed the hash ( sorry I was thinking that you modified the sed ( which is in different repo anyway ) :D

- so with this `npm i` will work, what won't work is installing via npm locally for development of `web-components` but that should be a separate issue in `skate-build` I guess. 

screen shot 2017-02-22 at 12 00 29 pm


Can you pls create issue for that @elmariofredo thx!

LGTM

**Comment by Hotell** [comment]
although CI got stuck, let's merge this.

**Pull request merged**
