### PR TITLE
chore: fix backtick escape replace

### LINKED ISSUE #40: build issue with sed command
When fixing #36 I have encounter issue with build specifically `sed` command here https://github.com/skatejs/web-components/blob/master/webpack.config.js#L16 I'm not sure why it stopped working did resolve issue with following awkward fix

```diff
diff --git a/webpack.config.js b/webpack.config.js
index 083c495..07ada10 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -13,7 +13,7 @@ conf.plugins.push(new WebpackShellPlugin({
   onBuildStart: [
     // Escape all backtick characters so we can wrap it in a template literal.
     // eslint-disable-next-line
-    'sed -e "s/\\\`/\\\\\\\\\\`/g" ./node_modules/@webcomponents/custom-elements/src/native-shim.js > ./src/native-shim.js',
+    'sed -e \x27s/`/\\\\`/g\x27 ./node_modules/@webcomponents/custom-elements/src/native-shim.js > ./src/native-shim.js',

     // Wrap in a conditional eval so it doesn't get executed in non-supported environments.
     'echo "window.customElements && eval(\\`$(cat ./src/native-shim.js)\\`);" > ./src/native-shim.js'
```

@treshugart can you please verify that it's working on your machine it's really strange that it's working on CI. If it's working for you let's close this issue.

### PR DESCRIPTION
**Pull request by devopsmariocom**
Closes #40

### CODE REVIEW

**Comment by devopsmariocom** [comment]
**DO NOT MERGE!** Resolving CI issue https://travis-ci.org/skatejs/web-components/builds/204153459#L433 which explains why it didn't fail on this issue

**Comment by devopsmariocom** [comment]
So I have find out that `onBuildEnd` was silently failing see [log](https://travis-ci.org/skatejs/web-components/builds/204153459#L433) as it was missing `dist` folder at time of copying. As a result we were missing `native-shim.js` in released packages. I suspect that this is culprit https://github.com/skatejs/build/blob/master/bin/sk-bundle#L3 but I couldn't reproduce it on local. 

**What is more important this fix doesn't work on [linux](https://hub.docker.com/r/kkarczmarczyk/node-yarn/) new escaping will deform `native-shim.js`.**

So I'm closing this PR and I think that proper solution to this issue would be 

1. create backtick replace loader( should be really simple https://github.com/webpack-contrib/raw-loader/blob/master/index.js#L8)
2. use https://github.com/kevlened/copy-webpack-plugin to copy `native-shim.js`

**Comment by micahscopes** [comment]
@elmariofredo I'm having a hard time understanding point (1)

A backtick replace loader?  Is the only point of that sed command to replace backticks with escaped backticks?  (Trying to understand all those \\\\\\'s 😮  )  Would the raw-loader just be using javascript to do what the sed command is doing? I don't think I understood that reference to  https://github.com/webpack-contrib/raw-loader/blob/master/index.js#L8

**Comment by devopsmariocom** [comment]
@micahscopes yes exactly it make \\\` from ` so whole native-shim file can be then encapsulated in backticks.

My point about loader is to create custom loader to replace backticks. Reference to raw-loader is only as an example how easy it would be to create replace-backtick-loader

Simply said we need some multi platform solution to this as according to my experience sed doesn't work the same even across POSIX.

**Comment by micahscopes** [comment]
@elmariofredo alright, that's exactly what I figured...  doesn't seem so bad!

**Comment by devopsmariocom** [comment]
@micahscopes great! let me know if you will need help with this.

Cheers 🍻

**Comment by treshugart** [comment]
`sed` was just an easy implementation. Can write a node script or whatever to do this if we need to.

**Comment by micahscopes** [comment]
I'm working on it now, should have it done after lunch.  Just gonna make a simple webpack plugin that should fit in the webpack config.

**Pull request closed without merging**
